baseURL: "https://benh7702.github.io/"
title: Ben Heskin
theme: PaperMod




enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2
        - name: Articles
          url: articles/
          weight: 3
        - name: CV
          url: cv/
          weight: 4 
        

params:
    description: "This website hosts Ben Heskin's projects, articles, CV, and contact information."
    author: Ben Heskin
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","articles","cv"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ben Heskin
          subtitle: "I am a graduate of Mathematics at Trinity College Dublin, with a focus in statistics and economics. I am particularly interested in Data Analysis, Finance, and Data Journalism "
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
        - name: Projects
          url: projects/
        - name: Articles
          url: articles/
        - name: CV
          url: cv/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ben.heskin77@gmail.com
        - name: Linkedin 
          url: https://www.linkedin.com/in/ben-heskin-8636811b8/?originalSubdomain=ie

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ben Heskin"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

  
